spring.application.name=anvay

## Database
spring.datasource.url=jdbc:mysql://localhost:3306/anvay
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Connection URL (Using the Host and Port from your image)
#spring.datasource.url=jdbc:mysql://anvay-swastikatinkhede-7df7.l.aivencloud.com:12534/defaultdb?ssl-mode=REQUIRED
#
## Credentials
#spring.datasource.username=avnadmin
#spring.datasource.password=AVNS_3qHqkOrnXtPvpqqCna_

## JPA/Hibernate Settings
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server
server.port=8081
spring.flyway.enabled=false

# JWT
app.jwt.secret=anvaySecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLongForSecurity
app.jwt.expiration-ms=86400000

# Super Admin
app.superadmin.name=Super Admin
app.superadmin.email=admin@anvay.com
app.superadmin.password=Admin@123

